import { useEffect, useMemo, useRef, useState } from "react";
import type { PointerEvent as ReactPointerEvent } from "react";

import type { HealthStatus, SessionConsent } from "../types";
import { toSimplifiedDisplay } from "../lib/display-text";
import { QidieAvatar } from "./QidieAvatar";
import { StatusMessage } from "./StoryLoom";

type FamiliarStoryCard = { title: string; cover: string };

const FAMILIAR_STORY_CARDS: Record<string, FamiliarStoryCard> = {
  boya_breaks_strings: { title: "伯牙绝弦", cover: "/assets/landing/corpus-boya-v1.webp" },
  butterfly_lovers: { title: "梁山伯与祝英台", cover: "/assets/landing/corpus-butterfly-lovers-v1.webp" },
  change_flight_to_moon: { title: "嫦娥奔月", cover: "/assets/landing/corpus-change-v1.webp" },
  cowherd_weaver_girl: { title: "牛郎织女", cover: "/assets/landing/corpus-cowherd-v1.webp" },
  gun_yu_flood_control: { title: "大禹治水", cover: "/assets/landing/card-dayu.webp" },
  houyi_shoots_suns: { title: "后羿射日", cover: "/assets/landing/corpus-houyi-v1.webp" },
  jingwei_fills_sea: { title: "精卫填海", cover: "/assets/landing/card-jingwei.webp" },
  kuafu_sun_chase: { title: "夸父逐日", cover: "/assets/landing/corpus-kuafu-v1.webp" },
  mengjiangnu_great_wall: { title: "孟姜女哭长城", cover: "/assets/landing/corpus-mengjiangnu-v1.webp" },
  mulan_substitution: { title: "花木兰从军", cover: "/assets/landing/corpus-mulan-v1.webp" },
  nanke_dream: { title: "南柯一梦", cover: "/assets/landing/corpus-nanke-v1.webp" },
  nvwa_mends_sky: { title: "女娲补天", cover: "/assets/landing/corpus-nvwa-v1.webp" },
  pangu_cosmogony: { title: "盘古开天", cover: "/assets/landing/corpus-pangu-v1.webp" },
  white_snake_legend: { title: "白蛇传", cover: "/assets/landing/corpus-white-snake-v1.webp" },
  yugong_moves_mountains: { title: "愚公移山", cover: "/assets/landing/corpus-yugong-v1.webp" },
  zhuangzhou_butterfly_dream: { title: "庄周梦蝶", cover: "/assets/landing/card-zhuangzhou.webp" },
};

const FALLBACK_FAMILY_IDS = [
  "boya_breaks_strings",
  "butterfly_lovers",
  "change_flight_to_moon",
  "cowherd_weaver_girl",
  "gun_yu_flood_control",
  "houyi_shoots_suns",
  "jingwei_fills_sea",
  "kuafu_sun_chase",
  "mengjiangnu_great_wall",
  "mulan_substitution",
  "nanke_dream",
  "nvwa_mends_sky",
] as const;

const DEMO_CASES = [
  {
    id: "new-team",
    tab: "接下新任务",
    label: "新团队里的临时任务",
    input: "第一次参加新团队例会，我主动接下合作任务，回去后却有点不安。",
    question: "你主动答应时，最先在意的是什么？后来又是什么让你开始不安？",
    story: "大禹治水",
    source: "采用《吴越春秋·越王无余外传》",
    reason: "把接手重担、重新选择方法与辨认责任边界放在一起比较——不是赞美过劳。",
    branch: "先问清共同责任与可用方法，再决定自己愿意承担到哪里。",
    finalLine: "承担，不等于独自扛下所有。",
  },
  {
    id: "plan-changed",
    tab: "计划忽然落空",
    label: "一个没有按计划发生的结果",
    input: "准备很久的机会突然取消，我知道还会有下一次，还是很难立刻放下。",
    question: "如果不急着把这件事说成好或坏，此刻最确定的损失是什么？仍未结束的变化又是什么？",
    story: "塞翁失马",
    source: "采用《淮南子·人间训》",
    reason: "它反复改变对同一事件的判断，但不会用未来的可能性否认当下真实的失落。",
    branch: "先承认已经落空的部分，再给尚未发生的变化留一处空白。",
    finalLine: "我可以暂时不知道，它最终意味着什么。",
  },
  {
    id: "long-project",
    tab: "长期推进受阻",
    label: "一件迟迟没有进展的长期工作",
    input: "这件事做了很久，眼前仍像一座山。我开始怀疑，坚持是不是只剩下消耗。",
    question: "你想继续的究竟是哪一部分？如果不再一个人搬动它，谁或什么可以加入？",
    story: "愚公移山",
    source: "采用《列子·汤问篇》愚公移山段",
    reason: "它不只讲坚持，也写家人、邻人与代际协作，适合重新拆分“独自坚持”这件事。",
    branch: "把遥远目标拆成可交接的小段，并允许同行者改变原来的路径。",
    finalLine: "山没有立刻变小，但路不再只由我一个人开。",
  },
] as const;

/* The three cards shown in the interface section. Titles and source works are
   real catalogue entries; the header art was generated by the product's own
   cover prompt, so the section shows what a card looks like rather than what a
   designer wished it looked like. */
const SHOWCASE_CARDS = [
  {
    slug: "jingwei",
    title: "精卫填海",
    source: "山海经·北山经",
    reason: "把“明知很难仍每天做一点”单独拿出来看，不预设这是执着还是徒劳。",
    alt: "《精卫填海》的白描题图：小鸟衔石立于浪上，远处有山",
  },
  {
    slug: "dayu",
    title: "大禹治水",
    source: "吴越春秋·越王无余外传",
    reason: "把接手重担、重新选择方法与辨认责任边界放在一起比较——不是赞美过劳。",
    alt: "《大禹治水》的白描题图：山口开凿处水流奔涌，一人执耒立于水畔",
  },
  {
    slug: "zhuangzhou",
    title: "庄周梦蝶",
    source: "庄子·齐物论",
    reason: "当“我是谁”本身成了问题时，它提供的是一种看待方式，不是答案。",
    alt: "《庄周梦蝶》的白描题图：伏几而卧的人与一只翩然的蝴蝶",
  },
] as const;

/* One node per mapping slot, canon on the left and the modern branch on the
   right — the same two-column relation the real canvas uses. */
const MAPPING_NODES = [
  { label: "召唤", canon: "受命治水", branch: "主动接下合作任务" },
  { label: "试炼", canon: "九年堵而不成", branch: "回去后不安，责任还没说清" },
  { label: "转折", canon: "改堵为疏", branch: "把任务带回团队，问清共同责任" },
  { label: "代价", canon: "三过家门不入", branch: "不把承担等同于独自扛下" },
  { label: "归返", canon: "百川归海", branch: "只接住自己确认的一段，共同推进" },
] as const;

const THEATRE_ACTS = ["接住火种", "光线成结", "把结摊开", "众人分线", "织成共图", "各执一端"] as const;

const HERO_STORY_WORDS = [
  { text: "神话", tone: "myth" },
  { text: "传奇", tone: "legend" },
  { text: "志怪", tone: "strange" },
  { text: "小说", tone: "fiction" },
] as const;

function useHeroStoryWord() {
  const [wordIndex, setWordIndex] = useState(0);
  const [visibleCharacters, setVisibleCharacters] = useState(0);
  const [deleting, setDeleting] = useState(false);
  const [reducedMotion, setReducedMotion] = useState(false);
  const currentWord = HERO_STORY_WORDS[wordIndex];

  useEffect(() => {
    if (typeof window.matchMedia !== "function") return undefined;
    const preference = window.matchMedia("(prefers-reduced-motion: reduce)");
    const syncPreference = () => setReducedMotion(preference.matches);
    syncPreference();
    preference.addEventListener?.("change", syncPreference);
    return () => preference.removeEventListener?.("change", syncPreference);
  }, []);

  useEffect(() => {
    if (reducedMotion) {
      if (wordIndex !== 0) setWordIndex(0);
      if (visibleCharacters !== HERO_STORY_WORDS[0].text.length) {
        setVisibleCharacters(HERO_STORY_WORDS[0].text.length);
      }
      if (deleting) setDeleting(false);
      return undefined;
    }

    let delay = deleting ? 140 : 210;
    let nextStep = () => setVisibleCharacters((count) => count + (deleting ? -1 : 1));

    if (!deleting && visibleCharacters === currentWord.text.length) {
      delay = 1_300;
      nextStep = () => setDeleting(true);
    } else if (deleting && visibleCharacters === 0) {
      delay = 280;
      nextStep = () => {
        setWordIndex((index) => (index + 1) % HERO_STORY_WORDS.length);
        setDeleting(false);
      };
    }

    const timer = window.setTimeout(nextStep, delay);
    return () => window.clearTimeout(timer);
  }, [currentWord.text.length, deleting, reducedMotion, visibleCharacters, wordIndex]);

  return {
    text: currentWord.text.slice(0, visibleCharacters),
    tone: currentWord.tone,
  };
}

export function ConsentScreen({
  busy,
  error,
  health,
  onBegin,
}: {
  busy: boolean;
  error: string | null;
  health: HealthStatus | null;
  onBegin: (consent: SessionConsent) => Promise<void>;
}) {
  const [modalOpen, setModalOpen] = useState(false);
  const [accepted, setAccepted] = useState(false);
  const [activeCaseId, setActiveCaseId] = useState<(typeof DEMO_CASES)[number]["id"]>(DEMO_CASES[0].id);
  const heroStoryWord = useHeroStoryWord();
  const closeButtonRef = useRef<HTMLButtonElement>(null);
  const modalRef = useRef<HTMLElement>(null);
  const previousFocusRef = useRef<HTMLElement | null>(null);
  const busyRef = useRef(busy);
  busyRef.current = busy;
  const overview = health?.corpusOverview;
  const recommendationCount = overview?.totalRecommendationCandidates
    ?? overview?.recommendationPoolStories
    ?? overview?.catalogUniqueStories
    ?? overview?.catalogEntries
    ?? 12_383;
  const sourceWorkCount = overview?.catalogSourceWorks
    || overview?.catalogWorks?.length
    || undefined;
  const featuredWorks = overview?.catalogWorks?.slice(0, 6) ?? [];
  const familyCards = useMemo(() => {
    const resolved = (overview?.familyIds ?? [])
      .map((familyId) => FAMILIAR_STORY_CARDS[familyId])
      .filter((card): card is FamiliarStoryCard => Boolean(card));
    const fallback = FALLBACK_FAMILY_IDS.map((familyId) => FAMILIAR_STORY_CARDS[familyId]);
    return [...resolved, ...fallback]
      .filter((card, index, cards) => cards.findIndex((item) => item.title === card.title) === index)
      .slice(0, 12);
  }, [overview?.familyIds]);
  const activeCase = DEMO_CASES.find((item) => item.id === activeCaseId) ?? DEMO_CASES[0];

  useEffect(() => {
    if (!modalOpen) return;
    closeButtonRef.current?.focus();
    function keepFocusInDialog(event: KeyboardEvent) {
      if (event.key === "Escape" && !busyRef.current) {
        setModalOpen(false);
        return;
      }
      if (event.key !== "Tab") return;
      const focusable = [...(modalRef.current?.querySelectorAll<HTMLElement>(
        'button:not([disabled]), input:not([disabled]), [href], [tabindex]:not([tabindex="-1"])',
      ) ?? [])];
      if (!focusable.length) return;
      const first = focusable[0];
      const last = focusable.at(-1) ?? first;
      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault();
        first.focus();
      }
    }
    window.addEventListener("keydown", keepFocusInDialog);
    return () => {
      window.removeEventListener("keydown", keepFocusInDialog);
      previousFocusRef.current?.focus();
    };
  }, [modalOpen]);

  useEffect(() => {
    const targets = [...document.querySelectorAll<HTMLElement>("[data-reveal]")];
    if (!("IntersectionObserver" in window)) {
      targets.forEach((target) => target.classList.add("is-visible"));
      return undefined;
    }
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        entry.target.classList.add("is-visible");
        observer.unobserve(entry.target);
      });
    }, { rootMargin: "0px 0px -12%", threshold: 0.12 });
    targets.forEach((target) => observer.observe(target));
    return () => observer.disconnect();
  }, []);

  function moveHero(event: ReactPointerEvent<HTMLElement>) {
    const bounds = event.currentTarget.getBoundingClientRect();
    const x = ((event.clientX - bounds.left) / bounds.width - 0.5) * 18;
    const y = ((event.clientY - bounds.top) / bounds.height - 0.5) * 12;
    event.currentTarget.style.setProperty("--hero-shift-x", `${x.toFixed(2)}px`);
    event.currentTarget.style.setProperty("--hero-shift-y", `${y.toFixed(2)}px`);
  }

  function resetHero(event: ReactPointerEvent<HTMLElement>) {
    event.currentTarget.style.setProperty("--hero-shift-x", "0px");
    event.currentTarget.style.setProperty("--hero-shift-y", "0px");
  }

  function begin() {
    const bundledConsent: SessionConsent = {
      adultConfirmed: accepted,
      nonClinicalAcknowledged: accepted,
      cloudProcessingAccepted: accepted,
      adultContentOptIn: accepted,
    };
    void onBegin(bundledConsent);
  }

  function openConsent() {
    previousFocusRef.current = document.activeElement instanceof HTMLElement
      ? document.activeElement
      : null;
    setModalOpen(true);
  }

  function closeConsent() {
    if (!busy) setModalOpen(false);
  }

  return (
    <main id="main" className="landing-page landing-page-v2">
      <section
        className="landing-hero landing-hero-cinematic"
        aria-labelledby="welcome-title"
        onPointerMove={moveHero}
        onPointerLeave={resetHero}
      >
        <div className="hero-art" aria-hidden="true">
          <div className="hero-art-image" />
          <div className="hero-ink-veil" />
          <div className="hero-mist hero-mist-a" />
          <div className="hero-mist hero-mist-b" />
          <img className="hero-floating-mark hero-floating-mark-a" src="/assets/mengdie-logo-mark-side-v5-transparent.png" alt="" />
          <img className="hero-floating-mark hero-floating-mark-b" src="/assets/mengdie-logo-mark-side-v5-transparent.png" alt="" />
        </div>

        <div className="landing-hero-copy">
          <p className="hero-edition"><span>中国古典神话传说</span><i aria-hidden="true" /><span>个人经历</span><i aria-hidden="true" /><span>共同续写</span></p>
          <p className="hero-wordmark">梦蝶记</p>
          <h1 id="welcome-title" aria-label="中国古典神话、传奇、志怪与小说，在你的此刻生出一条新支线。">
            <span aria-hidden="true">
              中国古典<span className={`hero-word-slot is-${heroStoryWord.tone}`}><span className="hero-rotating-word">{heroStoryWord.text}</span><i className="hero-type-caret" /></span>，
            </span>
            <br /><em>在你的此刻<br /><span className="hero-branch-line">生出一条新支线</span></em>
          </h1>
          <p className="welcome-lead">
            <strong>栖蝶——梦蝶记中的故事向导。</strong>把一件最近发生、你愿意讲的小事告诉它；它会先整理并请你确认，再从带有古籍出处的开发候选中寻找一则可供比较的故事。原典留在原典，你的选择写成新的现代支线。
          </p>
          <div id="hero-actions" className="landing-actions">
            <button id="hero-start" className="primary-action landing-primary" type="button" onClick={openConsent}>
              进入体验 <span aria-hidden="true">↗</span>
            </button>
            <a className="landing-text-link" href="#case-showcase">先看一次示例 <span aria-hidden="true">↓</span></a>
          </div>
          <div className="hero-trust" aria-label="体验边界">
            <span>来源可追溯</span><span>映照可修改</span><span>会话可删除</span>
          </div>
          <p className="landing-meta">约 12–15 分钟 · 面向成年用户</p>
        </div>

        <aside className="hero-signal-card" aria-label="栖蝶工作示意">
          <header>
            <div className="hero-guide-identity">
              <QidieAvatar size={38} className="hero-guide-avatar" />
              <p><strong>栖蝶</strong><span>故事向导</span></p>
            </div>
            <span className="hero-signal-status">整理过程示意</span>
          </header>
          <div className="hero-signal-thread">
            <p className="hero-signal-user"><span>你刚刚说</span>“我主动接下任务，回去后却有点不安。”</p>
            <div className="hero-signal-route" aria-hidden="true"><i /><i /><i /></div>
            <div className="hero-signal-result">
              <span className="hero-result-seal">水</span>
              <p><small>有出处的故事回应</small><strong>大禹治水</strong><span>接手重担，也重新选择方法。</span></p>
            </div>
          </div>
          <footer><span>推荐理由可读</span><span>故事可以拒绝</span></footer>
        </aside>

        <a className="hero-scroll-cue" href="#case-showcase"><span>继续了解</span><i aria-hidden="true" /></a>
      </section>

      <section id="case-showcase" className="landing-section case-showcase" aria-labelledby="case-title" data-reveal>
        <header className="landing-section-heading">
          <p className="section-label">案例 · 一次完整来回</p>
          <h2 id="case-title">一件真实小事，怎样走到一场可以改写的再演？</h2>
          <p>下面是体验路径示意，不是固定答案。你说的内容、选择的故事与最后一句，始终可以更改或拒绝。</p>
        </header>

        <div className="case-tabs" role="tablist" aria-label="切换示例体验">
          {DEMO_CASES.map((item, index) => (
            <button
              key={item.id}
              id={`case-tab-${item.id}`}
              type="button"
              role="tab"
              aria-selected={item.id === activeCase.id}
              aria-controls="case-demo-panel"
              onClick={() => setActiveCaseId(item.id)}
            >
              <span>{String(index + 1).padStart(2, "0")}</span>{item.tab}
            </button>
          ))}
        </div>

        <div
          key={activeCase.id}
          id="case-demo-panel"
          className="case-demo-panel"
          role="tabpanel"
          aria-live="polite"
          aria-labelledby={`case-tab-${activeCase.id}`}
        >
          <article className="case-moment case-moment-user">
            <p className="case-step">你说 · {activeCase.label}</p>
            <blockquote>“{activeCase.input}”</blockquote>
            <p className="case-note"><span>栖蝶先问</span>{activeCase.question}</p>
          </article>

          <article className="case-moment case-moment-source">
            <p className="case-step">有出处的故事回应</p>
            <div className="case-story-lockup">
              <span aria-hidden="true">典</span>
              <div><h3>{activeCase.story}</h3><p>{activeCase.source}</p></div>
            </div>
            <p>{activeCase.reason}</p>
            <small>推荐用于比较，不替你解释人生。</small>
          </article>

          <article className="case-moment case-moment-branch">
            <p className="case-step">你们共谱 · 仍由你批准</p>
            <p>{activeCase.branch}</p>
            <div className="case-final-line"><span>终幕收束句</span>“{activeCase.finalLine}”</div>
            <ul aria-label="用户可控操作"><li>修改五个映照节点</li><li>拒绝或换故事</li><li>命名、保存或删除</li></ul>
          </article>
        </div>
      </section>

      <section id="how-it-works" className="landing-section journey-section feature-section" aria-labelledby="journey-title" data-reveal>
        <div className="section-heading-block landing-section-heading">
          <h2 id="journey-title">从相遇到再演，决定权始终在你</h2>
          <p>栖蝶沿着你分享的那件事整理时间、人物与转折，说明推荐并起草映照；故事选择、修改与最终表达仍由你确认。</p>
        </div>
        <ol className="journey-list feature-chapters">
          <li>
            <span className="chapter-mark">相遇</span><small>第一阶段</small>
            <h3>先回应，再追问</h3>
            <p>从一件真实小事开始。只有你确认摘要后，系统才会给出带真实题名、采用文本与理由的候选。</p>
            <div className="feature-tags"><span>自然对话</span><span>摘要确认</span><span>可换一批</span></div>
          </li>
          <li>
            <span className="chapter-mark">共谱</span><small>第二阶段</small>
            <h3>原典在左，你执笔在右</h3>
            <p>五节点映照先形成可编辑初稿；你可以直接改，也可以请栖蝶修改。任何变化都先预览再应用。</p>
            <div className="feature-tags"><span>五节点画布</span><span>版本保留</span><span>逐处确认</span></div>
          </li>
          <li>
            <span className="chapter-mark">再演</span><small>第三阶段</small>
            <h3>把批准的支线演出来</h3>
            <p>4–7 幕场景、幕布与系统旁白共同组成再演；最后由你完成落款与收束动作。</p>
            <div className="feature-tags"><span>逐幕场景</span><span>声音控制</span><span>终幕落款</span></div>
          </li>
        </ol>
      </section>

      <section id="interface" className="landing-section interface-showcase" aria-labelledby="interface-title" data-reveal>
        <div className="section-heading-block landing-section-heading">
          <h2 id="interface-title">你会看到的三块界面</h2>
          <p>推荐卡牌、五节点共谱画布、逐幕再演剧场——下面是它们在体验中的样子。</p>
        </div>

        <figure className="showcase-cards">
          <figcaption>
            <span className="section-label">相遇 · 故事推荐</span>
            <h3>三则候选摊开在你面前</h3>
            <p>每张卡牌带白描题图、真实题名与采用出处，以及“推荐理由”。你可以整批换掉，也可以一则都不选。</p>
          </figcaption>
          <div className="showcase-card-fan" aria-label="推荐卡牌示意">
            {SHOWCASE_CARDS.map((card, index) => (
              <article
                className={`showcase-card${index === 1 ? " is-front" : ""}`}
                key={card.slug}
                aria-current={index === 1 ? "true" : undefined}
              >
                <img src={`/assets/landing/card-${card.slug}.webp`} alt={card.alt} loading="lazy" decoding="async" />
                <div className="showcase-card-body">
                  <h4>{card.title}</h4>
                  <small>采用《{card.source}》</small>
                  <p>{card.reason}</p>
                </div>
                {index === 1 && <span className="showcase-card-mark" aria-hidden="true">已选</span>}
              </article>
            ))}
          </div>
        </figure>

        <div className="showcase-pair">
          <figure className="showcase-canvas">
            <figcaption>
              <span className="section-label">共谱 · 五节点画布</span>
              <h3>原典在左，你执笔在右</h3>
            </figcaption>
            <ol className="canvas-nodes" aria-label="五个映照节点示意">
              {MAPPING_NODES.map((node) => (
                <li key={node.label}>
                  <span className="canvas-node-canon">{node.canon}</span>
                  <strong>{node.label}</strong>
                  <span className="canvas-node-branch">{node.branch}</span>
                </li>
              ))}
            </ol>
            <small>每个节点都能直接改写，或交给栖蝶改；改动先预览再应用。</small>
          </figure>

          <figure className="showcase-theatre">
            <figcaption>
              <span className="section-label">再演 · 共创剧场</span>
              <h3>你确认的支线，长成一则现代神话</h3>
            </figcaption>
            <div className="theatre-frame" aria-label="再演共创剧场六幕示意">
              <div className="theatre-artwork">
                <img
                  className="theatre-spread-image"
                  src="/assets/landing/theatre-new-team-modern-myth-v1.webp"
                  alt="现代共创神话六幕示例：主角主动接下合作任务，独处时被发光丝线缠住；随后把线结放回共同桌面，与伙伴分清各自愿意接住的一段、织成协作图，最终众人携线向前，光线汇成飞蝶。"
                  width="1536"
                  height="864"
                  loading="lazy"
                  decoding="async"
                />
                <span className="theatre-generation-note">现代支线示例 · AI 生成</span>
              </div>
              <div className="theatre-stage">
                <span className="theatre-act">第 3 幕 · 把结摊开</span>
                <p>下一次例会，主角把缠成结的任务放回共同的桌面：先问清哪些责任属于大家、有哪些方法可用，再决定自己愿意接住哪一段。</p>
              </div>
              <ol className="theatre-act-strip" aria-label="六幕画面顺序">
                {THEATRE_ACTS.map((act, index) => (
                  <li key={act} className={index === 2 ? "is-current" : ""} aria-current={index === 2 ? "step" : undefined}>
                    <span>{String(index + 1).padStart(2, "0")}</span>
                    <strong>{act}</strong>
                  </li>
                ))}
              </ol>
            </div>
            <p className="theatre-source-boundary"><strong>来源边界</strong> 大禹治水只提供“接下重担、遭遇阻力、改换方法”的比较线索；主动接下任务、问清共同责任与共同分工属于用户确认的现代支线。本组画面不复现原典情节，也不是古籍插图。</p>
            <small>首页展示“接下新任务”案例的共创结果；实际体验会根据你确认的支线生成 4–7 幕画面与旁白，也可以随时关掉声音。</small>
          </figure>
        </div>
      </section>

      <section id="technology" className="technology-section" aria-labelledby="technology-title" data-reveal>
        <div className="technology-inner">
          <header className="technology-heading">
            <h2 id="technology-title">一条有来源、有边界、<br />也有退路的生成链路</h2>
            <p>故事从可追溯的出处中被找到，你确认的现代支线独立保存；即使生成暂时不可用，体验也能继续。</p>
          </header>

          <ol className="technology-pipeline" aria-label="梦蝶记技术链路">
            <li><span>01</span><strong>先整理你说的</strong><p>先回应愿意分享的内容；摘要确认后才开始找故事。</p></li>
            <li><span>02</span><strong>在古籍中寻找</strong><p>只从可追溯的候选里寻找相近故事。</p></li>
            <li><span>03</span><strong>说明为何推荐</strong><p>比较情节与处境，并把理由写给你看。</p></li>
            <li><span>04</span><strong>检查来源边界</strong><p>确认题名、出处与改写没有混在一起。</p></li>
            <li><span>05</span><strong>保留继续路径</strong><p>暂时无法生成时，仍可完成这次体验。</p></li>
          </ol>

          <div className="technology-proof-grid">
            <article className="proof-source"><span><i aria-hidden="true" />原典</span><h3>来源与采用文本保持只读</h3><p>智能讲解与现代改写不会冒充原典。</p></article>
            <article className="proof-branch"><span><i aria-hidden="true" />你的支线</span><h3>每次修改独立保留</h3><p>只有你确认的版本才会进入剧场。</p></article>
            <article className="proof-seal"><span><i aria-hidden="true" />最终确认</span><h3>决定权始终在你</h3><p>印章只表示你的选择，不代表模型一定正确。</p></article>
          </div>

          <div className="technology-stats" aria-label="当前实现数字">
            <p><strong>{recommendationCount.toLocaleString("zh-CN")}</strong>{" "}<span>条可推荐候选</span></p>
            <p><strong>{sourceWorkCount ?? 6}</strong>{" "}<span>部开放古籍来源</span></p>
            <p><strong>4–7</strong>{" "}<span>幕动态再演</span></p>
          </div>
        </div>
      </section>

      <section id="corpus" className="landing-section corpus-section" aria-labelledby="corpus-title" data-reveal>
        <div className="corpus-stat-panel">
          <p className="section-label">故事来源</p>
          <h2 id="corpus-title"><strong>{recommendationCount.toLocaleString("zh-CN")}</strong> 条候选，<br />从出处开始</h2>
          <p className="corpus-status">
            这里的数字指机器切分后的开发候选，不等同于同等数量的独立故事。技术演示版尚未逐条完成人工复核，但候选都会保留题名与出处；每次体验只采用一份主文本{sourceWorkCount ? `。目前汇集 ${sourceWorkCount} 部古籍` : ""}。
          </p>
          {featuredWorks.length ? (
            <ul className="corpus-group-list" aria-label="部分来源古籍">
              {featuredWorks.map((work) => (
                <li key={work.sourceWorkId}>
                  <span>{toSimplifiedDisplay(work.title)}</span><strong>{work.count.toLocaleString("zh-CN")} 条</strong>
                </li>
              ))}
            </ul>
          ) : null}
        </div>
        <div className="corpus-shelf-wrap">
          <h3 className="shelf-title">生成卡面预览</h3>
          <div className="corpus-story-grid" aria-label="生成卡面预览">
            {familyCards.map((card) => (
              <article className="corpus-story-card" key={card.title}>
                <img src={card.cover} alt={`《${card.title}》白描封面`} loading="lazy" decoding="async" />
                <h4>{card.title}</h4>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="landing-final-cta" data-reveal>
        <div>
          <h2>你不必先懂神话，<br />只要带来一件愿意讲的小事</h2>
          <p>栖蝶会陪你走完相遇、共谱与再演；原典不会被改写，最终留下什么由你决定。</p>
          <button className="primary-action" type="button" onClick={openConsent}>和栖蝶开始 <span aria-hidden="true">↗</span></button>
        </div>
      </section>

      <footer className="landing-footer">
        <p><strong>梦蝶记</strong><span>中国古典神话传说与个人经历共谱</span></p>
        <p>成年用户文化叙事体验 · 非诊疗产品</p>
      </footer>

      {modalOpen && (
        <div className="consent-modal-backdrop" role="presentation" onMouseDown={(event) => {
          if (event.target === event.currentTarget) closeConsent();
        }}>
          <section ref={modalRef} className="consent-modal" role="dialog" aria-modal="true" aria-labelledby="consent-title" aria-describedby="consent-description consent-processing">
            <button ref={closeButtonRef} className="modal-close" type="button" aria-label="关闭确认弹窗" disabled={busy} onClick={closeConsent}>关闭</button>
            <p className="section-label">进入前确认</p>
            <h2 id="consent-title">请先了解这次体验</h2>
            <p id="consent-description">梦蝶记面向成年用户，是文化叙事体验而非诊疗。请不要填写姓名、联系方式、单位等可识别信息。</p>
            <p id="consent-processing" className="consent-processing">启用模型服务时，对话与映照文字会交由深度求索处理；获批支线的分幕画面会交由阿里云处理。旁白目前由你的设备朗读。本应用仅在服务内存中暂存会话，最迟二十四小时自动清除；这不代表第三方服务的留存期限。结束页可立即删除本应用中的会话。</p>
            <label className="consent-row consent-bundle">
              <input type="checkbox" checked={accepted} onChange={(event) => setAccepted(event.target.checked)} />
              <span><strong>我已年满十八岁，并理解和接受以上说明</strong></span>
            </label>
            <StatusMessage error={error} />
            <button className="primary-action consent-submit" type="button" disabled={!accepted || busy} onClick={begin}>
              {busy ? "正在建立会话…" : "确认并进入相遇"}
            </button>
          </section>
        </div>
      )}
    </main>
  );
}
